export const NetworkEvents = {
    // Client to Host
    DISCOVERY_REQUEST: 'DISCOVERY_REQUEST',
    INPUT: 'INPUT',

    // Host to Client
    DISCOVERY_RESPONSE: 'DISCOVERY_RESPONSE',
    SNAPSHOT: 'SNAPSHOT',
    INIT_WORLD: 'INIT_WORLD',
    UPDATE_HP: 'UPDATE_HP',
    ENTITY_DEATH: 'ENTITY_DEATH',
    HUMANS_ESCAPED: 'HUMANS_ESCAPED',
    PLAYER_ESCAPED: 'PLAYER_ESCAPED',
    PORTAL_SPAWN: 'PORTAL_SPAWN',
    RESPAWN_MONSTER: 'RESPAWN_MONSTER',
    EFFECT: 'EFFECT',
    FLOAT_TEXT: 'FLOAT_TEXT',
    SPAWN_PROJECTILE: 'SPAWN_PROJECTILE',
    UPDATE_GOLD: 'UPDATE_GOLD',
    LOOT_SUCCESS: 'LOOT_SUCCESS',
    UPDATE_INVENTORY: 'UPDATE_INVENTORY',
    LOOT_OPENED: 'LOOT_OPENED',
};

export const Intents = {
    MOVE: 'MOVE',
    TARGET_ACTION: 'TARGET_ACTION',
    PRIMARY_ACTION: 'PRIMARY_ACTION',
    EQUIP_ITEM: 'EQUIP_ITEM',
    UNEQUIP_ITEM: 'UNEQUIP_ITEM',
    DROP_ITEM: 'DROP_ITEM',
    INTERACT_LOOT: 'INTERACT_LOOT',
    USE_ABILITY_SLOT: 'USE_ABILITY_SLOT',
    PICKUP: 'PICKUP',
    ABILITY: 'ABILITY',
    TOGGLE_INVENTORY: 'TOGGLE_INVENTORY',
    TOGGLE_MENU: 'TOGGLE_MENU',
    AUTO_EXPLORE: 'AUTO_EXPLORE',
};
